Update BBRv3main.yml

diff --git a/.github/workflows/BBRv3main.yml b/.github/workflows/BBRv3main.yml
--- a/.github/workflows/BBRv3main.yml
+++ b/.github/workflows/BBRv3main.yml
@@ -3308,6 +3308,17 @@ jobs:
           # Inject into global build via CPPFLAGS
           echo '#include "linux/atomic/atomic64_fallback.h"' >> kernel_platform/common/include/linux/kernel.h
 
+      - name: Apply patch for raw_atomic64 and raw_atomic_long functions
+        run: |
+          # Apply the patch
+          git apply patches/atomic-long-fix.patch
+
+          # Check if the patch was applied successfully
+          if [ $? -ne 0 ]; then
+            echo "Failed to apply the patch"
+            exit 1
+          fi
+
 
       - name: Build Kernel
         working-directory: ${{ env.BUILD_DIR }}/${{ env.KERNEL_DIR }}/kernel_platform
